import React from 'react';
import './BldTrainerComponent.scss';

export default function BldTrainerComponent() {
    return (
        <div className='timer__bld-trainer-component'>
            <table className='basic-table'>
                <thead>
                    <tr>
                        <th className='bld-pair-column'></th>
                        {letterPairTable.map((letterPair, index) => {
                            return (
                                <th key={index} className='bld-pair-column'>
                                    {letterPair.letter}
                                </th>
                            );
                        })}
                    </tr>
                </thead>
                <tbody>
                    {letterPairTable.map((letterPair, index) => {
                        return (
                            <tr key={index}>
                                <td>{letterPair.letter}</td>
                                {letterPair.pairs.map((pair, index) => {
                                    return (
                                        <td
                                            key={index}
                                            className={pair.letter === letterPair.letter ? 'bld-pair--null' : ''}
                                        >
                                            {pair.word}
                                        </td>
                                    );
                                })}
                            </tr>
                        );
                    })}
                </tbody>
            </table>
        </div>
    );
}

const letterPairTable = [
    {
        letter: 'A',
        pairs: [
            { letter: 'A', word: '-' },
            { letter: 'B', word: 'Abs' },
            { letter: 'C', word: 'Ace' },
            { letter: 'D', word: 'Add' },
            { letter: 'E', word: '' },
            { letter: 'F', word: 'As Fuck' },
            { letter: 'G', word: 'Age' },
            { letter: 'H', word: 'Ahh' },
            { letter: 'I', word: 'Aid' },
            { letter: 'J', word: 'Apple Jacks' },
            { letter: 'K', word: 'Ask' },
            { letter: 'L', word: 'Ale' },
            { letter: 'M', word: 'Amp' },
            { letter: 'N', word: 'Ant' },
            { letter: 'O', word: 'AOC' },
            { letter: 'P', word: 'Ape' },
            { letter: 'Q', word: '' },
            { letter: 'R', word: 'Art' },
            { letter: 'S', word: 'Ass' },
            { letter: 'T', word: 'At' },
            { letter: 'U', word: 'August' },
            { letter: 'V', word: 'A/V' },
            { letter: 'W', word: 'Aww' },
            { letter: 'X', word: 'Ax' },
            { letter: 'Y', word: 'Aye' },
            { letter: 'Z', word: 'Azo' },
        ],
    },
    {
        letter: 'B',
        pairs: [
            { letter: 'A', word: 'Bay' },
            { letter: 'B', word: '-' },
            { letter: 'C', word: 'Back' },
            { letter: 'D', word: 'Bad' },
            { letter: 'E', word: 'Bee' },
            { letter: 'F', word: 'Boyfriend' },
            { letter: 'G', word: 'Big' },
            { letter: 'H', word: 'Boho' },
            { letter: 'I', word: 'Bi' },
            { letter: 'J', word: 'Blowjob' },
            { letter: 'K', word: 'Bike' },
            { letter: 'L', word: 'Ball' },
            { letter: 'M', word: 'Bomb' },
            { letter: 'N', word: 'Band' },
            { letter: 'O', word: 'Bo peep' },
            { letter: 'P', word: 'Boop' },
            { letter: 'Q', word: '' },
            { letter: 'R', word: 'Bro' },
            { letter: 'S', word: 'Boss' },
            { letter: 'T', word: 'Bat' },
            { letter: 'U', word: 'Butt' },
            { letter: 'V', word: 'Brave' },
            { letter: 'W', word: '' },
            { letter: 'X', word: 'Box' },
            { letter: 'Y', word: 'Bay' },
            { letter: 'Z', word: 'Bozo' },
        ],
    },
    {
        letter: 'C',
        pairs: [
            { letter: 'A', word: 'California' },
            { letter: 'B', word: 'Cab' },
            { letter: 'C', word: '-' },
            { letter: 'D', word: 'Cod' },
            { letter: 'E', word: '' },
            { letter: 'F', word: 'Coffin' },
            { letter: 'G', word: 'Cog' },
            { letter: 'H', word: 'Chop' },
            { letter: 'I', word: '' },
            { letter: 'J', word: 'CeeJay' },
            { letter: 'K', word: 'Cock' },
            { letter: 'L', word: 'Cold' },
            { letter: 'M', word: 'Camera' },
            { letter: 'N', word: 'Can' },
            { letter: 'O', word: 'Cone' },
            { letter: 'P', word: 'Cop' },
            { letter: 'Q', word: 'Croque' },
            { letter: 'R', word: 'Core' },
            { letter: 'S', word: 'Cost' },
            { letter: 'T', word: 'Coat' },
            { letter: 'U', word: 'Cut' },
            { letter: 'V', word: 'Cove' },
            { letter: 'W', word: 'Cow' },
            { letter: 'X', word: 'Cox' },
            { letter: 'Y', word: 'Cray' },
            { letter: 'Z', word: 'Crazy' },
        ],
    },
    {
        letter: 'D',
        pairs: [
            { letter: 'A', word: 'Day' },
            { letter: 'B', word: 'Dab' },
            { letter: 'C', word: 'DC' },
            { letter: 'D', word: '-' },
            { letter: 'E', word: 'Deedee' },
            { letter: 'F', word: 'Deaf' },
            { letter: 'G', word: 'Dog' },
            { letter: 'H', word: 'Dough' },
            { letter: 'I', word: 'Die' },
            { letter: 'J', word: 'DJ' },
            { letter: 'K', word: 'Donkey Kong' },
            { letter: 'L', word: 'Dill' },
            { letter: 'M', word: 'Dumb' },
            { letter: 'N', word: 'Den' },
            { letter: 'O', word: 'Doodoo' },
            { letter: 'P', word: 'Dip' },
            { letter: 'Q', word: 'Dairy Queen' },
            { letter: 'R', word: 'Door' },
            { letter: 'S', word: 'Desk' },
            { letter: 'T', word: 'Data' },
            { letter: 'U', word: 'Dude' },
            { letter: 'V', word: 'Dave' },
            { letter: 'W', word: 'Dweeb' },
            { letter: 'X', word: 'Dexter' },
            { letter: 'Y', word: 'Day' },
            { letter: 'Z', word: 'Daisy' },
        ],
    },
    {
        letter: 'E',
        pairs: [
            { letter: 'A', word: 'Ear' },
            { letter: 'B', word: 'EB Games' },
            { letter: 'C', word: 'Echo' },
            { letter: 'D', word: 'Eddy' },
            { letter: 'E', word: '-' },
            { letter: 'F', word: 'Enough' },
            { letter: 'G', word: 'Egg' },
            { letter: 'H', word: 'Ehh' },
            { letter: 'I', word: 'Early Integration' },
            { letter: 'J', word: 'Edge' },
            { letter: 'K', word: 'Eek' },
            { letter: 'L', word: 'Element' },
            { letter: 'M', word: 'Eminem' },
            { letter: 'N', word: 'End' },
            { letter: 'O', word: 'Eobard' },
            { letter: 'P', word: 'Episode' },
            { letter: 'Q', word: 'EQ' },
            { letter: 'R', word: 'Error' },
            { letter: 'S', word: 'Easter' },
            { letter: 'T', word: 'Phone home' },
            { letter: 'U', word: 'Europe' },
            { letter: 'V', word: 'EV car' },
            { letter: 'W', word: 'Eww' },
            { letter: 'X', word: 'Ex' },
            { letter: 'Y', word: 'Eye' },
            { letter: 'Z', word: 'Easy' },
        ],
    },
    {
        letter: 'F',
        pairs: [
            { letter: 'A', word: 'Fat' },
            { letter: 'B', word: 'Fabulous' },
            { letter: 'C', word: 'Face' },
            { letter: 'D', word: 'Food' },
            { letter: 'E', word: 'Fee' },
            { letter: 'F', word: '-' },
            { letter: 'G', word: 'Flag' },
            { letter: 'H', word: 'Fetch' },
            { letter: 'I', word: 'Fi' },
            { letter: 'J', word: 'Fudge' },
            { letter: 'K', word: 'Fuck' },
            { letter: 'L', word: 'Fall' },
            { letter: 'M', word: 'Family' },
            { letter: 'N', word: 'Fan' },
            { letter: 'O', word: 'Foe' },
            { letter: 'P', word: 'Flip' },
            { letter: 'Q', word: 'Farquad' },
            { letter: 'R', word: 'Afro' },
            { letter: 'S', word: 'Fast' },
            { letter: 'T', word: 'Fit' },
            { letter: 'U', word: 'Fun' },
            { letter: 'V', word: 'Favorite' },
            { letter: 'W', word: 'Fawn' },
            { letter: 'X', word: 'Fax' },
            { letter: 'Y', word: 'Fly' },
            { letter: 'Z', word: 'Frozen' },
        ],
    },
    {
        letter: 'G',
        pairs: [
            { letter: 'A', word: 'Gate' },
            { letter: 'B', word: 'GameBoy' },
            { letter: 'C', word: 'GameCube' },
            { letter: 'D', word: 'Good' },
            { letter: 'E', word: 'Gee' },
            { letter: 'F', word: 'Gift' },
            { letter: 'G', word: '-' },
            { letter: 'H', word: 'Ghost' },
            { letter: 'I', word: 'Gi' },
            { letter: 'J', word: 'Gauge' },
            { letter: 'K', word: 'Goku' },
            { letter: 'L', word: 'Gale' },
            { letter: 'M', word: 'Game' },
            { letter: 'N', word: 'Gin' },
            { letter: 'O', word: 'Go' },
            { letter: 'P', word: 'Gap' },
            { letter: 'Q', word: 'GQ Mag' },
            { letter: 'R', word: 'Grass' },
            { letter: 'S', word: 'Gas' },
            { letter: 'T', word: 'Goat' },
            { letter: 'U', word: 'Goo' },
            { letter: 'V', word: 'Gravel' },
            { letter: 'W', word: 'Grow' },
            { letter: 'X', word: 'Gecko' },
            { letter: 'Y', word: 'Gay' },
            { letter: 'Z', word: 'Gaze' },
        ],
    },
    {
        letter: 'H',
        pairs: [
            { letter: 'A', word: 'Haha' },
            { letter: 'B', word: 'Hobby' },
            { letter: 'C', word: '' },
            { letter: 'D', word: 'Hard' },
            { letter: 'E', word: 'He' },
            { letter: 'F', word: 'Hefty' },
            { letter: 'G', word: 'Hog' },
            { letter: 'H', word: '-' },
            { letter: 'I', word: 'Hi' },
            { letter: 'J', word: 'Hedge' },
            { letter: 'K', word: 'Heck' },
            { letter: 'L', word: 'Hell' },
            { letter: 'M', word: 'Ham' },
            { letter: 'N', word: 'Hen' },
            { letter: 'O', word: 'Hoe' },
            { letter: 'P', word: 'Hop' },
            { letter: 'Q', word: '' },
            { letter: 'R', word: 'Whore' },
            { letter: 'S', word: 'Hose' },
            { letter: 'T', word: 'Hot' },
            { letter: 'U', word: 'Human' },
            { letter: 'V', word: 'Heaven' },
            { letter: 'W', word: 'ohW' },
            { letter: 'X', word: 'Hacks' },
            { letter: 'Y', word: 'Hay' },
            { letter: 'Z', word: 'Haze' },
        ],
    },
    {
        letter: 'I',
        pairs: [
            { letter: 'A', word: 'Tiamat' },
            { letter: 'B', word: 'IBS' },
            { letter: 'C', word: 'Ice' },
            { letter: 'D', word: 'ID' },
            { letter: 'E', word: 'Internet Explorer' },
            { letter: 'F', word: 'Iffy' },
            { letter: 'G', word: 'Instagram' },
            { letter: 'H', word: 'iH' },
            { letter: 'I', word: '-' },
            { letter: 'J', word: 'Idget' },
            { letter: 'K', word: 'Ick' },
            { letter: 'L', word: 'Ill' },
            { letter: 'M', word: 'Important' },
            { letter: 'N', word: 'In' },
            { letter: 'O', word: 'I/O' },
            { letter: 'P', word: 'IP address' },
            { letter: 'Q', word: 'IQ' },
            { letter: 'R', word: 'Infrared' },
            { letter: 'S', word: 'Is' },
            { letter: 'T', word: 'It' },
            { letter: 'U', word: 'I&U' },
            { letter: 'V', word: 'Ivory' },
            { letter: 'W', word: 'Iwojima' },
            { letter: 'X', word: 'Nine' },
            { letter: 'Y', word: 'Ivy' },
            { letter: 'Z', word: 'Izzy' },
        ],
    },
    {
        letter: 'J',
        pairs: [
            { letter: 'A', word: 'Jail' },
            { letter: 'B', word: 'Job' },
            { letter: 'C', word: 'Jace' },
            { letter: 'D', word: 'JD' },
            { letter: 'E', word: 'Jeep' },
            { letter: 'F', word: 'Jeff' },
            { letter: 'G', word: 'Jog' },
            { letter: 'H', word: 'Jheart' },
            { letter: 'I', word: 'Jim' },
            { letter: 'J', word: '-' },
            { letter: 'K', word: 'Joke' },
            { letter: 'L', word: 'Jill' },
            { letter: 'M', word: 'Jam' },
            { letter: 'N', word: 'John' },
            { letter: 'O', word: 'Joe' },
            { letter: 'P', word: 'JP' },
            { letter: 'Q', word: 'Jeaque' },
            { letter: 'R', word: 'Jar' },
            { letter: 'S', word: 'Jesse' },
            { letter: 'T', word: 'Jet' },
            { letter: 'U', word: 'Juju' },
            { letter: 'V', word: 'Jive' },
            { letter: 'W', word: 'Jaw' },
            { letter: 'X', word: 'Jax' },
            { letter: 'Y', word: 'Jay' },
            { letter: 'Z', word: 'JayZee' },
        ],
    },
    {
        letter: 'K',
        pairs: [
            { letter: 'A', word: 'Kay' },
            { letter: 'B', word: 'Kobe' },
            { letter: 'C', word: 'caKe' },
            { letter: 'D', word: 'Kid' },
            { letter: 'E', word: 'Keefer' },
            { letter: 'F', word: 'Koffing' },
            { letter: 'G', word: 'Keg' },
            { letter: 'H', word: 'Kindhearted' },
            { letter: 'I', word: 'Kick' },
            { letter: 'J', word: 'Kedge' },
            { letter: 'K', word: '-' },
            { letter: 'L', word: 'Kelle' },
            { letter: 'M', word: 'Kim' },
            { letter: 'N', word: 'Ken' },
            { letter: 'O', word: 'Akido' },
            { letter: 'P', word: 'Kippy' },
            { letter: 'Q', word: 'KroKay' },
            { letter: 'R', word: 'Krow' },
            { letter: 'S', word: 'Kiss' },
            { letter: 'T', word: 'Kit' },
            { letter: 'U', word: 'Kiuper belt' },
            { letter: 'V', word: 'Kevin' },
            { letter: 'W', word: 'Kawkaw' },
            { letter: 'X', word: 'Kix' },
            { letter: 'Y', word: 'Kay' },
            { letter: 'Z', word: 'Katz' },
        ],
    },
    {
        letter: 'L',
        pairs: [
            { letter: 'A', word: 'Los Angeles' },
            { letter: 'B', word: 'Lab' },
            { letter: 'C', word: 'Lace' },
            { letter: 'D', word: 'Ladel' },
            { letter: 'E', word: 'Lee' },
            { letter: 'F', word: 'Leaf' },
            { letter: 'G', word: 'Leg' },
            { letter: 'H', word: 'Laugh' },
            { letter: 'I', word: 'Lie' },
            { letter: 'J', word: 'Ledge' },
            { letter: 'K', word: 'Lick' },
            { letter: 'L', word: '-' },
            { letter: 'M', word: 'Limb' },
            { letter: 'N', word: 'Lentel' },
            { letter: 'O', word: 'Low' },
            { letter: 'P', word: 'Lap' },
            { letter: 'Q', word: 'Lake' },
            { letter: 'R', word: 'Lair' },
            { letter: 'S', word: 'Lass' },
            { letter: 'T', word: 'Light' },
            { letter: 'U', word: 'Lulu' },
            { letter: 'V', word: 'Lava' },
            { letter: 'W', word: 'Law' },
            { letter: 'X', word: 'Lax' },
            { letter: 'Y', word: 'Lay' },
            { letter: 'Z', word: 'Lazy' },
        ],
    },
    {
        letter: 'M',
        pairs: [
            { letter: 'A', word: 'Mama' },
            { letter: 'B', word: 'Mob' },
            { letter: 'C', word: 'Mice' },
            { letter: 'D', word: 'Mad' },
            { letter: 'E', word: 'Me' },
            { letter: 'F', word: 'Motherfucker' },
            { letter: 'G', word: 'Magazine' },
            { letter: 'H', word: 'My heart' },
            { letter: 'I', word: 'Mii' },
            { letter: 'J', word: 'Michael Jackson' },
            { letter: 'K', word: 'Mike' },
            { letter: 'L', word: 'Mail' },
            { letter: 'M', word: '-' },
            { letter: 'N', word: 'Mine' },
            { letter: 'O', word: 'Moe' },
            { letter: 'P', word: 'Map' },
            { letter: 'Q', word: 'Mecha' },
            { letter: 'R', word: 'Mr.' },
            { letter: 'S', word: 'Master' },
            { letter: 'T', word: 'Matt' },
            { letter: 'U', word: 'Mew' },
            { letter: 'V', word: 'Mohave' },
            { letter: 'W', word: 'Maw' },
            { letter: 'X', word: 'Max' },
            { letter: 'Y', word: 'My' },
            { letter: 'Z', word: 'Maze' },
        ],
    },
    {
        letter: 'N',
        pairs: [
            { letter: 'A', word: 'Nana' },
            { letter: 'B', word: 'Numb' },
            { letter: 'C', word: 'Nice' },
            { letter: 'D', word: 'Ned' },
            { letter: 'E', word: 'Neat' },
            { letter: 'F', word: 'Nifty' },
            { letter: 'G', word: 'Noggin' },
            { letter: 'H', word: 'Mash' },
            { letter: 'I', word: 'Ni' },
            { letter: 'J', word: 'Nudge' },
            { letter: 'K', word: 'Nick' },
            { letter: 'L', word: 'Null' },
            { letter: 'M', word: 'Enemy' },
            { letter: 'N', word: '-' },
            { letter: 'O', word: 'No' },
            { letter: 'P', word: 'Napster' },
            { letter: 'Q', word: 'Neck' },
            { letter: 'R', word: 'Nora' },
            { letter: 'S', word: 'Nest' },
            { letter: 'T', word: 'Net' },
            { letter: 'U', word: 'New' },
            { letter: 'V', word: 'Naive' },
            { letter: 'W', word: 'No way' },
            { letter: 'X', word: 'Next' },
            { letter: 'Y', word: 'Neigh' },
            { letter: 'Z', word: 'Nose' },
        ],
    },
    {
        letter: 'O',
        pairs: [
            { letter: 'A', word: 'Oat' },
            { letter: 'B', word: 'Orb' },
            { letter: 'C', word: 'Orange County' },
            { letter: 'D', word: 'Odie' },
            { letter: 'E', word: 'Olé' },
            { letter: 'F', word: 'Of' },
            { letter: 'G', word: 'Oak Grove' },
            { letter: 'H', word: 'Oh' },
            { letter: 'I', word: 'Oil' },
            { letter: 'J', word: 'Orange Juice' },
            { letter: 'K', word: 'Okay' },
            { letter: 'L', word: 'Old' },
            { letter: 'M', word: 'Omastar' },
            { letter: 'N', word: 'On' },
            { letter: 'O', word: '-' },
            { letter: 'P', word: 'Opa' },
            { letter: 'Q', word: 'Oh Quick' },
            { letter: 'R', word: 'Or' },
            { letter: 'S', word: 'Operating System' },
            { letter: 'T', word: 'Otter' },
            { letter: 'U', word: 'Out' },
            { letter: 'V', word: 'Over' },
            { letter: 'W', word: 'Ow' },
            { letter: 'X', word: 'Ox' },
            { letter: 'Y', word: 'Oyster' },
            { letter: 'Z', word: 'Oz' },
        ],
    },
    {
        letter: 'P',
        pairs: [
            { letter: 'A', word: 'Papa' },
            { letter: 'B', word: 'Pibb' },
            { letter: 'C', word: 'Pace' },
            { letter: 'D', word: 'Pad' },
            { letter: 'E', word: 'Pee' },
            { letter: 'F', word: 'Piff' },
            { letter: 'G', word: 'Peg' },
            { letter: 'H', word: 'Phone' },
            { letter: 'I', word: 'Pie' },
            { letter: 'J', word: 'Pajamas' },
            { letter: 'K', word: 'Pack' },
            { letter: 'L', word: 'Pill' },
            { letter: 'M', word: 'Pam' },
            { letter: 'N', word: 'Pen' },
            { letter: 'O', word: 'Poe' },
            { letter: 'P', word: '-' },
            { letter: 'Q', word: 'Peck' },
            { letter: 'R', word: 'Poor' },
            { letter: 'S', word: 'Post' },
            { letter: 'T', word: 'Pet' },
            { letter: 'U', word: 'Poo' },
            { letter: 'V', word: 'Pave' },
            { letter: 'W', word: 'Paw' },
            { letter: 'X', word: 'Pax' },
            { letter: 'Y', word: 'Pay' },
            { letter: 'Z', word: 'Pez' },
        ],
    },
    {
        letter: 'Q',
        pairs: [
            { letter: 'A', word: 'Quack' },
            { letter: 'B', word: 'Quarterback' },
            { letter: 'C', word: 'Quick' },
            { letter: 'D', word: 'Quad' },
            { letter: 'E', word: 'Qué' },
            { letter: 'F', word: 'Queef' },
            { letter: 'G', word: '' },
            { letter: 'H', word: 'Quohog' },
            { letter: 'I', word: 'Qi' },
            { letter: 'J', word: 'Quedge' },
            { letter: 'K', word: 'Quake' },
            { letter: 'L', word: 'Quill' },
            { letter: 'M', word: 'Quartermaster' },
            { letter: 'N', word: '' },
            { letter: 'O', word: 'Quo' },
            { letter: 'P', word: 'Quip' },
            { letter: 'Q', word: '-' },
            { letter: 'R', word: 'Quart' },
            { letter: 'S', word: 'Quest' },
            { letter: 'T', word: 'Quit' },
            { letter: 'U', word: 'Qu' },
            { letter: 'V', word: 'Quiver' },
            { letter: 'W', word: '' },
            { letter: 'X', word: '' },
            { letter: 'Y', word: '' },
            { letter: 'Z', word: '' },
        ],
    },
    {
        letter: 'R',
        pairs: [
            { letter: 'A', word: '' },
            { letter: 'B', word: '' },
            { letter: 'C', word: '' },
            { letter: 'D', word: '' },
            { letter: 'E', word: '' },
            { letter: 'F', word: '' },
            { letter: 'G', word: '' },
            { letter: 'H', word: '' },
            { letter: 'I', word: '' },
            { letter: 'J', word: '' },
            { letter: 'K', word: '' },
            { letter: 'L', word: '' },
            { letter: 'M', word: '' },
            { letter: 'N', word: '' },
            { letter: 'O', word: '' },
            { letter: 'P', word: '' },
            { letter: 'Q', word: '' },
            { letter: 'R', word: '-' },
            { letter: 'S', word: '' },
            { letter: 'T', word: '' },
            { letter: 'U', word: '' },
            { letter: 'V', word: '' },
            { letter: 'W', word: '' },
            { letter: 'X', word: '' },
            { letter: 'Y', word: '' },
            { letter: 'Z', word: '' },
        ],
    },
    {
        letter: 'S',
        pairs: [
            { letter: 'A', word: '' },
            { letter: 'B', word: '' },
            { letter: 'C', word: '' },
            { letter: 'D', word: '' },
            { letter: 'E', word: '' },
            { letter: 'F', word: '' },
            { letter: 'G', word: '' },
            { letter: 'H', word: '' },
            { letter: 'I', word: '' },
            { letter: 'J', word: '' },
            { letter: 'K', word: '' },
            { letter: 'L', word: '' },
            { letter: 'M', word: '' },
            { letter: 'N', word: '' },
            { letter: 'O', word: '' },
            { letter: 'P', word: '' },
            { letter: 'Q', word: '' },
            { letter: 'R', word: '' },
            { letter: 'S', word: '-' },
            { letter: 'T', word: '' },
            { letter: 'U', word: '' },
            { letter: 'V', word: '' },
            { letter: 'W', word: '' },
            { letter: 'X', word: '' },
            { letter: 'Y', word: '' },
            { letter: 'Z', word: '' },
        ],
    },
    {
        letter: 'T',
        pairs: [
            { letter: 'A', word: '' },
            { letter: 'B', word: '' },
            { letter: 'C', word: '' },
            { letter: 'D', word: '' },
            { letter: 'E', word: '' },
            { letter: 'F', word: '' },
            { letter: 'G', word: '' },
            { letter: 'H', word: '' },
            { letter: 'I', word: '' },
            { letter: 'J', word: '' },
            { letter: 'K', word: '' },
            { letter: 'L', word: '' },
            { letter: 'M', word: '' },
            { letter: 'N', word: '' },
            { letter: 'O', word: '' },
            { letter: 'P', word: '' },
            { letter: 'Q', word: '' },
            { letter: 'R', word: '' },
            { letter: 'S', word: '' },
            { letter: 'T', word: '-' },
            { letter: 'U', word: '' },
            { letter: 'V', word: '' },
            { letter: 'W', word: '' },
            { letter: 'X', word: '' },
            { letter: 'Y', word: '' },
            { letter: 'Z', word: '' },
        ],
    },
    {
        letter: 'U',
        pairs: [
            { letter: 'A', word: '' },
            { letter: 'B', word: '' },
            { letter: 'C', word: '' },
            { letter: 'D', word: '' },
            { letter: 'E', word: '' },
            { letter: 'F', word: '' },
            { letter: 'G', word: '' },
            { letter: 'H', word: '' },
            { letter: 'I', word: '' },
            { letter: 'J', word: '' },
            { letter: 'K', word: '' },
            { letter: 'L', word: '' },
            { letter: 'M', word: '' },
            { letter: 'N', word: '' },
            { letter: 'O', word: '' },
            { letter: 'P', word: '' },
            { letter: 'Q', word: '' },
            { letter: 'R', word: '' },
            { letter: 'S', word: '' },
            { letter: 'T', word: '' },
            { letter: 'U', word: '-' },
            { letter: 'V', word: '' },
            { letter: 'W', word: '' },
            { letter: 'X', word: '' },
            { letter: 'Y', word: '' },
            { letter: 'Z', word: '' },
        ],
    },
    {
        letter: 'V',
        pairs: [
            { letter: 'A', word: '' },
            { letter: 'B', word: '' },
            { letter: 'C', word: '' },
            { letter: 'D', word: '' },
            { letter: 'E', word: '' },
            { letter: 'F', word: '' },
            { letter: 'G', word: '' },
            { letter: 'H', word: '' },
            { letter: 'I', word: '' },
            { letter: 'J', word: '' },
            { letter: 'K', word: '' },
            { letter: 'L', word: '' },
            { letter: 'M', word: '' },
            { letter: 'N', word: '' },
            { letter: 'O', word: '' },
            { letter: 'P', word: '' },
            { letter: 'Q', word: '' },
            { letter: 'R', word: '' },
            { letter: 'S', word: '' },
            { letter: 'T', word: '' },
            { letter: 'U', word: '' },
            { letter: 'V', word: '-' },
            { letter: 'W', word: '' },
            { letter: 'X', word: '' },
            { letter: 'Y', word: '' },
            { letter: 'Z', word: '' },
        ],
    },
    {
        letter: 'W',
        pairs: [
            { letter: 'A', word: '' },
            { letter: 'B', word: '' },
            { letter: 'C', word: '' },
            { letter: 'D', word: '' },
            { letter: 'E', word: '' },
            { letter: 'F', word: '' },
            { letter: 'G', word: '' },
            { letter: 'H', word: '' },
            { letter: 'I', word: '' },
            { letter: 'J', word: '' },
            { letter: 'K', word: '' },
            { letter: 'L', word: '' },
            { letter: 'M', word: '' },
            { letter: 'N', word: '' },
            { letter: 'O', word: '' },
            { letter: 'P', word: '' },
            { letter: 'Q', word: '' },
            { letter: 'R', word: '' },
            { letter: 'S', word: '' },
            { letter: 'T', word: '' },
            { letter: 'U', word: '' },
            { letter: 'V', word: '' },
            { letter: 'W', word: '-' },
            { letter: 'X', word: '' },
            { letter: 'Y', word: '' },
            { letter: 'Z', word: '' },
        ],
    },
    {
        letter: 'X',
        pairs: [
            { letter: 'A', word: '' },
            { letter: 'B', word: '' },
            { letter: 'C', word: '' },
            { letter: 'D', word: '' },
            { letter: 'E', word: '' },
            { letter: 'F', word: '' },
            { letter: 'G', word: '' },
            { letter: 'H', word: '' },
            { letter: 'I', word: '' },
            { letter: 'J', word: '' },
            { letter: 'K', word: '' },
            { letter: 'L', word: '' },
            { letter: 'M', word: '' },
            { letter: 'N', word: '' },
            { letter: 'O', word: '' },
            { letter: 'P', word: '' },
            { letter: 'Q', word: '' },
            { letter: 'R', word: '' },
            { letter: 'S', word: '' },
            { letter: 'T', word: '' },
            { letter: 'U', word: '' },
            { letter: 'V', word: '' },
            { letter: 'W', word: '' },
            { letter: 'X', word: '-' },
            { letter: 'Y', word: '' },
            { letter: 'Z', word: '' },
        ],
    },
    {
        letter: 'Y',
        pairs: [
            { letter: 'A', word: '' },
            { letter: 'B', word: '' },
            { letter: 'C', word: '' },
            { letter: 'D', word: '' },
            { letter: 'E', word: '' },
            { letter: 'F', word: '' },
            { letter: 'G', word: '' },
            { letter: 'H', word: '' },
            { letter: 'I', word: '' },
            { letter: 'J', word: '' },
            { letter: 'K', word: '' },
            { letter: 'L', word: '' },
            { letter: 'M', word: '' },
            { letter: 'N', word: '' },
            { letter: 'O', word: '' },
            { letter: 'P', word: '' },
            { letter: 'Q', word: '' },
            { letter: 'R', word: '' },
            { letter: 'S', word: '' },
            { letter: 'T', word: '' },
            { letter: 'U', word: '' },
            { letter: 'V', word: '' },
            { letter: 'W', word: '' },
            { letter: 'X', word: '' },
            { letter: 'Y', word: '-' },
            { letter: 'Z', word: '' },
        ],
    },
    {
        letter: 'Z',
        pairs: [
            { letter: 'A', word: '' },
            { letter: 'B', word: '' },
            { letter: 'C', word: '' },
            { letter: 'D', word: '' },
            { letter: 'E', word: '' },
            { letter: 'F', word: '' },
            { letter: 'G', word: '' },
            { letter: 'H', word: '' },
            { letter: 'I', word: '' },
            { letter: 'J', word: '' },
            { letter: 'K', word: '' },
            { letter: 'L', word: '' },
            { letter: 'M', word: '' },
            { letter: 'N', word: '' },
            { letter: 'O', word: '' },
            { letter: 'P', word: '' },
            { letter: 'Q', word: '' },
            { letter: 'R', word: '' },
            { letter: 'S', word: '' },
            { letter: 'T', word: '' },
            { letter: 'U', word: '' },
            { letter: 'V', word: '' },
            { letter: 'W', word: '' },
            { letter: 'X', word: '' },
            { letter: 'Y', word: '' },
            { letter: 'Z', word: '-' },
        ],
    },
];
